name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install modules
        run: |
          corepack enable
          yarn install --frozen-lockfile
      - name: Lint
        run: yarn run lint
      - name: Run tests
        run: yarn run test
